### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [antonioscalaunina/ANTI-FASc#5]
I suggest adding topics such as `earthquake`, `tsunami` in the About section at https://github.com/antonioscalaunina/ANTI-FASc

**Comment by antonioscalaunina** [comment]
Thank you for the suggestion. I added those topics

**Comment by Beliavsky** [comment]
`tsunami` and `tsunamis` are considered distinct topics, and the former has more hits, so I suggest adding `tsunami` in addition to or instead of `tsunamis`. It is possible to do a topic search with `topic:some_topic`.
